### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Tamer173** [qbcore-framework/qb-weathersync#57]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
3. Use this item '....' (item's name from shared.lua if applicable)

**Expected behavior**
This Problem is here for last2 years Please Fix it

**Screenshots**
![Screenshot_2](https://user-images.githubusercontent.com/105336574/178981412-ce25c176-f2e2-469f-b2d6-044e961a877f.png)

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]
 - Today
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
 - no custom resorce
 - Have you renamed `qb-` to something custom? [e.g. yes/no]
 - no

**Additional context**

**Comment by Re1ease** [comment]
I haven't been able to reproduce the error. Please try the steps below and let me know if it fixed the error or not. 

- Update qb-weathersync to the latest version.
- Update your artifacts to the latest stable version.

**Comment by Tamer173** [comment]
Fixed tha6

**Comment by ThatOneShmuck** [comment]
I tried the steps above. Im having the same issue still, and have tried every possible solution that I could find.
